/*
	== DO NOT EDIT THIS FILE! ==
	This is necessary to keep paths correct for the minification process
*/
enyo.depends(
        "../lib/enyo/source/boot",
        "../lib/enyo/source/kernel",
        "../lib/enyo/source/ajax",
        //"../lib/enyo/source/dom",
        //"../lib/enyo/source",
        "../source"
);
